# Building Multiple Linear Regression Model

- This time we use **MULTIPLE features** instead of just one!

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
# import seaborn as sns

#changing the work directory
os.chdir(r'C:\Users\ongja\Downloads\Intro_ML\Module4')
df = pd.read_csv("Synergix_data_preprocessed_new.csv")
df.info()

In [14]:
# One-hot encode the 'Segment' column
df_encoded = pd.get_dummies(df, columns=['Segment'], drop_first=True)

# Display the first few rows of the modified dataset
df_encoded.head()

,Page_traffic,Unit_price,Units_sold,1_Star_Rating,2_Star_Rating,3_Star_Rating,4_Star_Rating,5_Star_Rating,Image_Count,Bullet_Count,...,Online_Cost,Online_Impressions,num_unique_campaigns,Clicks_video,Cost_video,Impressions_video,num_unique_campaigns_offline,Units_sold>1000,Segment_Makeup,Segment_Skincare
0,5835.0,22.214389,2071,99.0,72.0,194.0,453.0,3272.0,6.0,6.0,...,3102.448115,238075.0,6.0,3479.0,40244.28,3856872.0,2.0,1,False,True
1,1881.0,11.870778,681,118.0,73.0,200.0,430.0,3084.0,9.0,8.0,...,1723.716359,75868.0,2.0,0.0,0.00,0.0,0.0,0,False,True
2,2477.0,27.645714,875,108.0,85.0,232.0,511.0,3402.0,10.0,7.0,...,0.000000,0.0,0.0,0.0,0.00,0.0,0.0,0,True,False
3,4087.0,16.896848,1396,82.0,64.0,167.0,303.0,2058.0,5.0,7.0,...,0.000000,0.0,0.0,0.0,0.00,0.0,0.0,1,True,False
4,1446.0,16.357664,822,29.0,24.0,88.0,200.0,1221.0,0.0,8.0,...,0.000000,0.0,0.0,6024.0,77040.81,7539723.0,2.0,0,False,False

In [15]:
# Notice Segment Makeup and Skincare has data type of boolean.
df_encoded.dtypes

Page_traffic                    float64
Unit_price                      float64
Units_sold                        int64
1_Star_Rating                   float64
2_Star_Rating                   float64
3_Star_Rating                   float64
4_Star_Rating                   float64
5_Star_Rating                   float64
Image_Count                     float64
Bullet_Count                    float64
Title_Count                     float64
Description_Length              float64
num_unique_Search_Terms         float64
Organic Search Rank             float64
Num_of_Promotions               float64
Sum of Spend                    float64
Online_Clicks                   float64
Online_Cost                     float64
Online_Impressions              float64
num_unique_campaigns            float64
Clicks_video                    float64
Cost_video                      float64
Impressions_video               float64
num_unique_campaigns_offline    float64
Units_sold>1000                   int64
Segment_Makeup                     bool
Segment_Skincare                   bool
dtype: object

In [ ]:
# Using lambda function to convert True/False to 1/0

df_encoded['Segment_Makeup'] = df_encoded['Segment_Makeup'].apply(lambda x: 1 if x == True else 0)
df_encoded['Segment_Skincare'] = df_encoded['Segment_Skincare'].apply(lambda x: 1 if x == True else 0)

- Statsmodels needs numeric values, not boolean
- Boolean True/False → Numeric 1/0

In [18]:
df_encoded.head()

,Page_traffic,Unit_price,Units_sold,1_Star_Rating,2_Star_Rating,3_Star_Rating,4_Star_Rating,5_Star_Rating,Image_Count,Bullet_Count,...,Online_Cost,Online_Impressions,num_unique_campaigns,Clicks_video,Cost_video,Impressions_video,num_unique_campaigns_offline,Units_sold>1000,Segment_Makeup,Segment_Skincare
0,5835.0,22.214389,2071,99.0,72.0,194.0,453.0,3272.0,6.0,6.0,...,3102.448115,238075.0,6.0,3479.0,40244.28,3856872.0,2.0,1,0,1
1,1881.0,11.870778,681,118.0,73.0,200.0,430.0,3084.0,9.0,8.0,...,1723.716359,75868.0,2.0,0.0,0.00,0.0,0.0,0,0,1
2,2477.0,27.645714,875,108.0,85.0,232.0,511.0,3402.0,10.0,7.0,...,0.000000,0.0,0.0,0.0,0.00,0.0,0.0,0,1,0
3,4087.0,16.896848,1396,82.0,64.0,167.0,303.0,2058.0,5.0,7.0,...,0.000000,0.0,0.0,0.0,0.00,0.0,0.0,1,1,0
4,1446.0,16.357664,822,29.0,24.0,88.0,200.0,1221.0,0.0,8.0,...,0.000000,0.0,0.0,6024.0,77040.81,7539723.0,2.0,0,0,0

#### Remove Data Leakage Column

**data leakage** - contains information about the target

In [19]:
df_encoded.drop('Units_sold>1000', axis =1, inplace = True)

#### Separate Features (X) and Target (y)

In [20]:
X = df_encoded.drop('Units_sold', axis = 1)
y = df_encoded['Units_sold']

In [21]:
# Since we are using descriptive approach to study the satistic of the model, we use statsmodel library
import statsmodels.api as sm

In [ ]:
# Add constant term to features (X)
X_with_const = sm.add_constant(X)

# Note: We add contant term to features ONLY! Not target variable as target variable are data we WANT 
# to predict, adding constant term will modify the data.

# Fit the Multiple Linear Regression Model
model_reduced = sm.OLS(y, X_with_const).fit()

# Display the summary of the refitted model
model_reduced.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:             Units_sold   R-squared:                       0.461
Model:                            OLS   Adj. R-squared:                  0.461
Method:                 Least Squares   F-statistic:                     671.5
Date:                Wed, 18 Feb 2026   Prob (F-statistic):               0.00
Time:                        11:16:47   Log-Likelihood:            -1.4185e+05
No. Observations:               19631   AIC:                         2.837e+05
Df Residuals:                   19605   BIC:                         2.839e+05
Df Model:                          25
Covariance Type:            nonrobust
================================================================================================
                                   coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                          626.0215     22.979     27.243      0.000     580.981     671.062
Page_traffic                     0.1714      0.002     98.799      0.000       0.168       0.175
Unit_price                     -13.3938      0.328    -40.891      0.000     -14.036     -12.752
1_Star_Rating                    0.3558      0.269      1.324      0.185      -0.171       0.883
2_Star_Rating                    0.6141      0.522      1.176      0.240      -0.410       1.638
3_Star_Rating                    0.0684      0.219      0.312      0.755      -0.361       0.498
4_Star_Rating                   -0.2051      0.172     -1.194      0.233      -0.542       0.132
5_Star_Rating                    0.0258      0.017      1.481      0.139      -0.008       0.060
Image_Count                      7.2872      0.520     14.003      0.000       6.267       8.307
Bullet_Count                    -1.2477      4.022     -0.310      0.756      -9.131       6.636
Title_Count                      0.2161      0.124      1.736      0.083      -0.028       0.460
Description_Length               0.3391      0.053      6.378      0.000       0.235       0.443
num_unique_Search_Terms         -6.2509      0.883     -7.081      0.000      -7.981      -4.521
Organic Search Rank             -0.1440      0.212     -0.680      0.497      -0.559       0.271
Num_of_Promotions              -44.8287     10.794     -4.153      0.000     -65.986     -23.672
Sum of Spend                    -0.0132      0.019     -0.707      0.480      -0.050       0.023
Online_Clicks                   -0.1378      0.017     -8.138      0.000      -0.171      -0.105
Online_Cost                      0.0184      0.003      6.074      0.000       0.012       0.024
Online_Impressions              -0.0003   6.61e-05     -4.773      0.000      -0.000      -0.000
num_unique_campaigns            47.2523      2.426     19.479      0.000      42.497      52.007
Clicks_video                    -0.1008      0.011     -9.345      0.000      -0.122      -0.080
Cost_video                       0.0145      0.001     10.051      0.000       0.012       0.017
Impressions_video            -6.952e-05   7.95e-06     -8.744      0.000   -8.51e-05   -5.39e-05
num_unique_campaigns_offline    27.5439      4.213      6.538      0.000      19.287      35.801
Segment_Makeup                  77.1720      7.355     10.493      0.000      62.756      91.588
Segment_Skincare                67.4317      7.820      8.623      0.000      52.104      82.759
==============================================================================
Omnibus:                       87.027   Durbin-Watson:                   2.007
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              115.775
Skew:                           0.054   Prob(JB):                     7.24e-26
Kurtosis:                       3.360   Cond. No.                     4.23e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.23e+07. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

# Checking the VIF Scores

- Mutigating Multicollinearity
    - **Multicollinearity** means features are highly correlated with EACH OTHER

**VIF** measures how much the variance of a coefficient is "inflated" due to **correlation** with other features.

In [23]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

#### Create VIF Calculation Function
- For EACH feature, it runs a regression using ALL OTHER features as predictors
- Calculates R² for that regression
- using formula: **VIF = 1 / (1 - R²)**

In [24]:
#function to calculate the VIF score
def calculate_vif(data):
    """Calculate VIF for a dataframe."""
    vif_data = pd.DataFrame()
    vif_data["Variable"] = data.columns
    vif_data["VIF"] = [variance_inflation_factor(data.values, i) for i in range(data.shape[1])]
    return vif_data

calculate_vif(X)

                        Variable         VIF
0                   Page_traffic    6.232415
1                     Unit_price    8.808648
2                  1_Star_Rating   82.510990
3                  2_Star_Rating  157.034906
4                  3_Star_Rating  204.193130
5                  4_Star_Rating  515.106058
6                  5_Star_Rating  232.134449
7                    Image_Count    3.187786
8                   Bullet_Count   63.973549
9                    Title_Count   33.759326
10            Description_Length   11.105260
11       num_unique_Search_Terms    3.910526
12           Organic Search Rank    3.782835
13             Num_of_Promotions    2.226197
14                  Sum of Spend    2.164311
15                 Online_Clicks   23.033029
16                   Online_Cost    9.597947
17            Online_Impressions   13.287082
18          num_unique_campaigns    5.877044
19                  Clicks_video  356.303805
20                    Cost_video  826.782697
21             Impressions_video  206.284588
22  num_unique_campaigns_offline   11.785568
23                Segment_Makeup    4.777908
24              Segment_Skincare    3.259755

# Removing Features with VIF Scores > 10
1. Find feature with highest VIF
2. Remove it
3. Recalculate VIF for remaining features until all features VIF < 10

In [25]:
# Iteratively remove features with the highest VIF
VIF_threshold = 10
max_vif = float('inf')

while max_vif > VIF_threshold:
    # Calculate VIF
    vif_df = calculate_vif(X)
    
    # Find the max VIF
    max_vif = vif_df["VIF"].max()
    
    # If above threshold, remove that variable
    if max_vif > VIF_threshold:
        remove = vif_df.sort_values("VIF", ascending=False).iloc[0]
        
        # Drop the worst offender
        X.drop(remove["Variable"], axis=1, inplace=True)

# Display the features and their VIFs after the iterative removal
final_vif = calculate_vif(X)
final_vif.sort_values(by='VIF', ascending = False)

                        Variable       VIF
12             Impressions_video  9.285569
13  num_unique_campaigns_offline  8.565469
9                    Online_Cost  7.889338
1                     Unit_price  6.749765
10            Online_Impressions  5.986092
4             Description_Length  5.738634
11          num_unique_campaigns  5.383161
0                   Page_traffic  5.143528
14                Segment_Makeup  4.021865
2                  5_Star_Rating  3.805051
5        num_unique_Search_Terms  3.742886
6            Organic Search Rank  3.580233
3                    Image_Count  3.030420
15              Segment_Skincare  2.745083
7              Num_of_Promotions  2.216452
8                   Sum of Spend  2.117190

In [26]:
# Data for regression
X.shape, y.shape

((19631, 16), (19631,))

Observation:
- Reduced from ~25 features to ~16 features!

#### Refit Model

In [27]:
# Add a constant for the intercept term
X_with_const = sm.add_constant(X)

# Fit the regression model using statsmodels
model = sm.OLS(y, X_with_const).fit()

**R² Comparison:**  
- Before VIF removal: R² = 0.461
- After VIF removal:  R² = 0.45x (slightly lower)

In [ ]:
# Display the model summary
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:             Units_sold   R-squared:                       0.456
Model:                            OLS   Adj. R-squared:                  0.455
Method:                 Least Squares   F-statistic:                     1027.
Date:                Wed, 18 Feb 2026   Prob (F-statistic):               0.00
Time:                        12:15:20   Log-Likelihood:            -1.4194e+05
No. Observations:               19631   AIC:                         2.839e+05
Df Residuals:                   19614   BIC:                         2.841e+05
Df Model:                          16
Covariance Type:            nonrobust
================================================================================================
                                   coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                          647.4740     14.428     44.878      0.000     619.195     675.753
Page_traffic                     0.1692      0.002     99.058      0.000       0.166       0.173
Unit_price                     -13.6403      0.327    -41.688      0.000     -14.282     -12.999
5_Star_Rating                    0.0284      0.002     12.711      0.000       0.024       0.033
Image_Count                      7.2754      0.501     14.521      0.000       6.293       8.258
Description_Length               0.3983      0.041      9.758      0.000       0.318       0.478
num_unique_Search_Terms         -6.4975      0.868     -7.490      0.000      -8.198      -4.797
Organic Search Rank             -0.1331      0.212     -0.629      0.530      -0.548       0.282
Num_of_Promotions              -50.7222     10.818     -4.689      0.000     -71.926     -29.518
Sum of Spend                    -0.0252      0.019     -1.361      0.173      -0.061       0.011
Online_Cost                      0.0105      0.003      3.787      0.000       0.005       0.016
Online_Impressions              -0.0007   4.46e-05    -16.434      0.000      -0.001      -0.001
num_unique_campaigns            40.3797      2.333     17.307      0.000      35.807      44.953
Impressions_video            -8.221e-06    1.7e-06     -4.845      0.000   -1.15e-05   -4.89e-06
num_unique_campaigns_offline    29.0028      3.608      8.038      0.000      21.930      36.076
Segment_Makeup                  78.1933      7.309     10.698      0.000      63.867      92.519
Segment_Skincare                66.4372      7.849      8.465      0.000      51.053      81.821
==============================================================================
Omnibus:                      102.580   Durbin-Watson:                   2.007
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              137.652
Skew:                           0.068   Prob(JB):                     1.29e-30
Kurtosis:                       3.387   Cond. No.                     2.81e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.81e+07. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

# Removing Features with P-Values > 0.05

**Why p > 0.05 matters**:  
- p-value <= 0.05: Feature is statistically significant (has real effect)
- p-value > 0.05: Could be due to random chance (no proven effect)

In [29]:
#A quick look at the p-values
model.pvalues

const                           0.000000e+00
Page_traffic                    0.000000e+00
Unit_price                      0.000000e+00
5_Star_Rating                   7.204300e-37
Image_Count                     1.578992e-47
Description_Length              1.920461e-22
num_unique_Search_Terms         7.188356e-14
Organic Search Rank             5.295872e-01
Num_of_Promotions               2.767746e-06
Sum of Spend                    1.734653e-01
Online_Cost                     1.529211e-04
Online_Impressions              2.769220e-60
num_unique_campaigns            1.294451e-66
Impressions_video               1.275920e-06
num_unique_campaigns_offline    9.672873e-16
Segment_Makeup                  1.226200e-26
Segment_Skincare                2.741172e-17
dtype: float64

#### Identify Non-Significant Features

In [30]:
# Features with p > 0.05
features_to_remove = model.pvalues[model.pvalues > 0.05].index

# Don't remove the constant!
if 'const' in features_to_remove:
    features_to_remove = features_to_remove.drop('const')
    
print(features_to_remove)

Index(['Organic Search Rank', 'Sum of Spend'], dtype='object')

##### Drop Non-Significant Features

In [ ]:
# Drop those features
X = X.drop(columns=features_to_remove)
X.head()

Now we have:
- ✅ Low multicollinearity (VIF < 10)
- ✅ All features statistically significant (p < 0.05)
- A **clean, parsimonious** model!

#### Optional - Feature Scaling

- Scale Features Data

In [31]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Convert the scaled numpy array back back to DataFrame
X_scaled_df = pd.DataFrame(X_scaled, columns=X.columns)
X_scaled_df.head()

,Page_traffic,Unit_price,5_Star_Rating,Image_Count,Description_Length,num_unique_Search_Terms,Organic Search Rank,Num_of_Promotions,Sum of Spend,Online_Cost,Online_Impressions,num_unique_campaigns,Impressions_video,num_unique_campaigns_offline,Segment_Makeup,Segment_Skincare
0,1.703204,0.094899,1.243063,-0.168022,0.005376,-0.337033,-1.380061,-0.341256,-0.234496,0.843904,1.521245,2.460962,0.390454,0.587250,-1.086840,1.444183
1,-0.914797,-1.236958,1.101515,0.444920,0.136899,2.637922,-0.256217,-0.341256,-0.234496,0.127406,-0.025720,0.261051,-0.714274,-0.639296,-1.086840,1.444183
2,-0.520177,0.794244,1.340942,0.649235,0.745192,-0.039538,0.089581,-0.341256,-0.234496,-0.768373,-0.749271,-0.838904,-0.714274,-0.639296,0.920098,-0.692433
3,0.545828,-0.589795,0.329025,-0.372337,1.123320,0.852949,0.089581,-0.341256,-0.234496,-0.768373,-0.749271,-0.838904,-0.714274,-0.639296,0.920098,-0.692433
4,-1.202817,-0.659221,-0.301165,-1.393908,0.284862,-0.039538,-0.256217,-0.341256,-0.234496,-0.768373,-0.749271,-0.838904,1.445337,0.587250,-1.086840,-0.692433

In [35]:
# Add constant and fit final model
X_scaled_const = sm.add_constant(X_scaled_df)
final_desc_model = sm.OLS(y, X_scaled_const).fit()

print(final_desc_model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             Units_sold   R-squared:                       0.456
Model:                            OLS   Adj. R-squared:                  0.455
Method:                 Least Squares   F-statistic:                     1027.
Date:                Wed, 18 Feb 2026   Prob (F-statistic):               0.00
Time:                        13:13:11   Log-Likelihood:            -1.4194e+05
No. Observations:               19631   AIC:                         2.839e+05
Df Residuals:                   19614   BIC:                         2.841e+05
Df Model:                          16
Covariance Type:            nonrobust
================================================================================================
                                   coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------
const                         1115.6042      2.386    467.549      0.000    1110.927    1120.281
Page_traffic                   255.5959      2.580     99.058      0.000     250.538     260.653
Unit_price                    -105.9344      2.541    -41.688      0.000    -110.915    -100.954
5_Star_Rating                   37.6672      2.963     12.711      0.000      31.859      43.476
Image_Count                     35.6091      2.452     14.521      0.000      30.802      40.416
Description_Length              24.2268      2.483      9.758      0.000      19.360      29.093
num_unique_Search_Terms        -21.8406      2.916     -7.490      0.000     -27.556     -16.125
Organic Search Rank             -1.5399      2.450     -0.629      0.530      -6.341       3.261
Num_of_Promotions              -15.7863      3.367     -4.689      0.000     -22.386      -9.187
Sum of Spend                    -4.6065      3.384     -1.361      0.173     -11.240       2.027
Online_Cost                     20.1443      5.319      3.787      0.000       9.718      30.571
Online_Impressions             -76.7844      4.672    -16.434      0.000     -85.943     -67.626
num_unique_campaigns            73.4206      4.242     17.307      0.000      65.106      81.736
Impressions_video              -28.7005      5.924     -4.845      0.000     -40.312     -17.089
num_unique_campaigns_offline    47.2919      5.884      8.038      0.000      35.759      58.825
Segment_Makeup                  38.9615      3.642     10.698      0.000      31.823      46.100
Segment_Skincare                31.0946      3.673      8.465      0.000      23.895      38.295
==============================================================================
Omnibus:                      102.580   Durbin-Watson:                   2.007
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              137.652
Skew:                           0.068   Prob(JB):                     1.29e-30
Kurtosis:                       3.387   Cond. No.                         5.76
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [33]:
X_scaled_df.head()

,Page_traffic,Unit_price,5_Star_Rating,Image_Count,Description_Length,num_unique_Search_Terms,Organic Search Rank,Num_of_Promotions,Sum of Spend,Online_Cost,Online_Impressions,num_unique_campaigns,Impressions_video,num_unique_campaigns_offline,Segment_Makeup,Segment_Skincare
0,1.703204,0.094899,1.243063,-0.168022,0.005376,-0.337033,-1.380061,-0.341256,-0.234496,0.843904,1.521245,2.460962,0.390454,0.587250,-1.086840,1.444183
1,-0.914797,-1.236958,1.101515,0.444920,0.136899,2.637922,-0.256217,-0.341256,-0.234496,0.127406,-0.025720,0.261051,-0.714274,-0.639296,-1.086840,1.444183
2,-0.520177,0.794244,1.340942,0.649235,0.745192,-0.039538,0.089581,-0.341256,-0.234496,-0.768373,-0.749271,-0.838904,-0.714274,-0.639296,0.920098,-0.692433
3,0.545828,-0.589795,0.329025,-0.372337,1.123320,0.852949,0.089581,-0.341256,-0.234496,-0.768373,-0.749271,-0.838904,-0.714274,-0.639296,0.920098,-0.692433
4,-1.202817,-0.659221,-0.301165,-1.393908,0.284862,-0.039538,-0.256217,-0.341256,-0.234496,-0.768373,-0.749271,-0.838904,1.445337,0.587250,-1.086840,-0.692433